In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics

#Reading CSV File 

In [2]:
loan=pd.read_csv("Loan_Prediction.csv")
loan.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

# Deleting Loan_ID and CoapplicantIncome column

In [3]:
del loan["Loan_ID"]
del loan["CoapplicantIncome"]

# **CHANGING STRING VALUES TO INTEGER**

# For Gender Column

In [4]:
def fun(s):
    if(s=="Male"):
        return 1
    elif(s=="Female"):
        return 0

loan["Gender"]=loan.Gender.apply(fun)

#For Married Column

In [5]:
def fun(s):
    if(s=="Yes"):
        return 1
    elif(s=="No"):
        return 0

loan["Married"]=loan.Married.apply(fun)

# For Education Column

In [6]:
def fun(s):
    if(s=="Graduate"):
        return 1
    elif(s=="Not Graduate"):
        return 0

loan["Education"]=loan.Education.apply(fun)

# For Self_Employed Column

In [7]:
def fun(s):
    if(s=="Yes"):
        return 1
    elif(s=="No"):
        return 0

loan["Self_Employed"]=loan.Self_Employed.apply(fun)

# For Property_Area Column

In [8]:
def fun(s):
    if(s=="Urban"):
        return 2
    elif(s=="Rural"):
        return 1
    elif(s=="Semiurban"):
        return 0

loan["Property_Area"]=loan.Property_Area.apply(fun)

# For Loan_Status Column

In [9]:
def fun(s):
    if(s=="Y"):
        return 1
    elif(s=="N"):
        return 0

loan["Loan_Status"]=loan.Loan_Status.apply(fun)

# For Dependents Column

In [10]:
def fun(s):
    if(s=="3+"):
        return 3
    elif(s=="1"):
        return 1
    elif(s=="0"):
        return 0
    elif(s=="2"):
        return 2

loan["Dependents"]=loan.Dependents.apply(fun)

In [11]:
loan.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0     1.0      0.0         0.0          1            0.0             5849   
1     1.0      1.0         1.0          1            0.0             4583   
2     1.0      1.0         0.0          1            1.0             3000   
3     1.0      1.0         0.0          0            0.0             2583   
4     1.0      0.0         0.0          1            0.0             6000   

   LoanAmount  Loan_Amount_Term  Credit_History  Property_Area  Loan_Status  
0         NaN             360.0             1.0              2            1  
1       128.0             360.0             1.0              1            0  
2        66.0             360.0             1.0              2            1  
3       120.0             360.0             1.0              2            1  
4       141.0             360.0             1.0              2            1

# **CHECKING FOR NULL VALUES**

In [14]:
loan.isna().sum()

Gender              13
Married              3
Dependents          15
Education            0
Self_Employed       32
ApplicantIncome      0
LoanAmount          22
Loan_Amount_Term    14
Credit_History      50
Property_Area        0
Loan_Status          0
dtype: int64

# Calculating mean and median for NAN values

In [15]:
gender=loan["Gender"].median()
married=loan["Married"].median()
dependents=loan["Dependents"].median()
selfemp=loan["Self_Employed"].median()
loanamount=loan["LoanAmount"].mean()
term=loan["Loan_Amount_Term"].mean()
credhis=loan["Credit_History"].median()
gender,married,dependents,selfemp,loanamount,term,credhis

(1.0, 1.0, 0.0, 0.0, 146.41216216216216, 342.0, 1.0)

# **Replacing NULL values with mean and median**

In [16]:
loan.shape

(614, 11)

In [17]:
loan['Gender']=loan['Gender'].fillna(gender)
loan['Married']=loan['Married'].fillna(married)
loan['Dependents']=loan['Dependents'].fillna(dependents)
loan['Self_Employed']=loan['Self_Employed'].fillna(selfemp)
loan['LoanAmount']=loan['LoanAmount'].fillna(loanamount)
loan['Loan_Amount_Term']=loan['Loan_Amount_Term'].fillna(term)
loan['Credit_History']=loan['Credit_History'].fillna(credhis)

In [18]:
loan.isna().sum()

Gender              0
Married             0
Dependents          0
Education           0
Self_Employed       0
ApplicantIncome     0
LoanAmount          0
Loan_Amount_Term    0
Credit_History      0
Property_Area       0
Loan_Status         0
dtype: int64

# **Splitting Input and Output columns**

In [ ]:
Y=np.array(loan["Loan_Status"])
del loan["Loan_Status"]

In [ ]:
X=loan.values
X.shape,Y.shape

((614, 10), (614,))

# splitting into testing and training

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=0)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((460, 10), (154, 10), (460,), (154,))

# **Prediction using Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(x_train,y_train)
y_pred1=clf.predict(x_test)

In [ ]:
print("the accuracy is : ", metrics.accuracy_score(y_test,y_pred1),'\n')
print("Confusion Matrix : \n", metrics.confusion_matrix(y_test,y_pred1))

the accuracy is :  0.8311688311688312 

Confusion Matrix : 
 [[ 19  24]
 [  2 109]]


# **Prediction using SVM**

In [ ]:
from sklearn.svm import SVC 

classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_train, y_train)  
y_pred2=classifier.predict(x_test)

In [ ]:
print("the accuracy is : ", metrics.accuracy_score(y_test,y_pred2),'\n')
print("Confusion Matrix : \n", metrics.confusion_matrix(y_test,y_pred2))

the accuracy is :  0.8311688311688312 

Confusion Matrix : 
 [[ 19  24]
 [  2 109]]


# **Prediction Using KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=3)  
classifier.fit(x_train, y_train)  
y_pred3=classifier.predict(x_test)

In [ ]:
print("the accuracy is : ", metrics.accuracy_score(y_test,y_pred3),'\n')
print("Confusion Matrix : \n", metrics.confusion_matrix(y_test,y_pred3))

the accuracy is :  0.6363636363636364 

Confusion Matrix : 
 [[16 27]
 [29 82]]


# **Prediction Using Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_pred4=gnb.predict(x_test)

In [ ]:
print("the accuracy is : ", metrics.accuracy_score(y_test,y_pred4),'\n')
print("Confusion Matrix : \n", metrics.confusion_matrix(y_test,y_pred4))

the accuracy is :  0.8246753246753247 

Confusion Matrix : 
 [[ 19  24]
 [  3 108]]


# **Using Auto ML**

In [ ]:
!pip install auto-sklearn
import autosklearn

In [ ]:
import autosklearn.classification
cls = autosklearn.classification.AutoSklearnClassifier(time_left_for_this_task=60)
cls.fit(x_train, y_train)
predictions = cls.predict(x_test)

In [ ]:
print("the accuracy is : ", metrics.accuracy_score(y_test,predictions),'\n')
print("Confusion Matrix : \n", metrics.confusion_matrix(y_test,predictions))

the accuracy is :  0.8246753246753247 

Confusion Matrix : 
 [[ 20  23]
 [  4 107]]
